apiVersion: v1
kind: Service
metadata:
  name: calendar-service
spec:
  selector:
    app: calendar-app
  ports:
    - protocol: TCP
      name: grpc
      port: 8888
      targetPort: 8888
    - protocol: TCP
      name: rest
      port: 7777
      targetPort: 7777

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-app
  labels:
    app: calendar-app
spec:

  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
      - name: calendar-app
        image: murashkosv91/calendar-app:latest
        ports:
        - containerPort: 8888
        - containerPort: 7777
