apiVersion: v1
kind: Service
metadata:
  name: calendar-service
spec:
  selector:
    app: calendar-app
  ports:
    - protocol: TCP
      name: grpc
      port: 8888
      targetPort: 8888
    - protocol: TCP
      name: rest
      port: 7777
      targetPort: 7777
