logger:
  level: "info"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbName: "calendar"
  inMemory: false
server:
  host: "localhost"
  port: 7777
  hostgrpc: "localhost"
  portgrpc: 8888
