
mb:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  exchange: "calendar"
  exchangeType: "direct"
  routingKey: "calendar"
  reliable: true
  intervalCheck: 5
  notifyInterval: 1
logger:
  level: "info"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbName: "calendar"
  inMemory: false