
mb:
  rmq:
    host: "rabbitmq"
    port: 5672
    user: "sergey"
    password: "murashko"
    exchange: "calendar"
    exchangeType: "direct"
    routingKey: "calendar_routing_key"
  intervalCheck: 5
logger:
  level: "info"
db:
  host: "postgresql"
  port: 5432
  user: "otus"
  password: "otus"
  dbName: "calendar"
  inMemory: false