
mb:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  exchange: "calendar"
  exchangeType: "direct"
  queue: "calendar_q"
  bindKey: "calendar_routing_key"
  consumerTag: "sender_tag"
logger:
  level: "info"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbName: "calendar"
  inMemory: false